### ISSUE TITLE
Set bucket policy to authorise user to use bucket rather than using user policy

### ISSUE THREAD

**Issue by tm-kn** [torchbox/buckup#10]
To limit the amount of IAM permissions user has to have to create a bucket we should set user permissions on the bucket itself, e.g.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowUserManageBucket",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::1111111:user/bucket-s3-user"
            },
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation",
                "s3:ListBucketMultipartUploads",
                "s3:ListBucketVersions"
            ],
            "Resource": "arn:aws:s3:::bucket"
        },
        {
            "Sid": "AllowUserManageBucketObjects",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::1111111111:user/bucket-s3-user"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::bucket/*"
        }
    ]
}
```

**Comment by tomusher** [comment]
Yeah can do - that does mean you need the creating user to have permissions to update bucket policies, so we'd need to limit that permission to certain buckets. Could limit it to those starting with `buckup-` but that does mean they could still grant access to other project buckets.

**Comment by tm-kn** [comment]
Thanks @tomusher! Does that also mean that we can limit users to creating buckets (not only changing policy) that only have `buckup-` in the name?

**Comment by tomusher** [comment]
I'm not aware of a way of doing that, but it might be possible... it would probably be up to the tool to enforce that.

**Comment by tm-kn** [comment]
I don't think we need to be that granual with not letting people change bucket policies if that requires making program less generic. :P As long as we can avoid privilege escalation it's good enough in my eyes.
