### ISSUE TITLE
Pypi version requires old version of buckup

### ISSUE THREAD

**Issue by kevinhowbrook** [torchbox/buckup#14]
When installing buckup from pypi, the version of `boto` is 1.7.84.

In the code here on github it looks like it's using the latest [version](https://github.com/torchbox/buckup/blob/master/setup.cfg#L33-L34)
 
To recreate
- make a fresh venv
- pip install buckup
- pip freeze > reqs.txt

Observe boot version 1.7.84

**Workaround**
`pip install boto3==1.17.59`

**Fix**
I imagine we just need a new pypi build released?

**Comment by thibaudcolas** [comment]
I’ve released the existing `0.1a4` to PyPI, so you should now be able to do either of:

```bash
pip install buckup==0.1a4
# Or:
pip install --upgrade buckup
```
